imports:
  - BatteryTempSensor.runnable
  - ThermalInterfaces.interfaces

stimulus:
  kind: cyclic
  cycle_ms: 10
  offset_ms: 0

input_ports: []

output_ports:
  - name: output
    type: BatteryTempMsg

runnable_instances:
  - name: sensor
    type: BatteryTempSensor

connections:
  inputs: []
  graph: []
  outputs:
    - from: sensor.output
      to: output
